### PR TITLE
Rewrite the syntax

### PR DESCRIPTION
**Pull request by imbrish**
Hey!

I'm delivering on my promise from https://github.com/idleberg/sublime-innosetup/issues/8 to "look into it" 😏

After a quick fix I went on and completely rewrote the syntax. Now it is way more robust. And then I also updated the completions.
Now highlighting works very well in all Inno Setup examples and is also capable of showing some basic errors.
Was a nice exercise and I learned a thing or two.

Hope you like it!

### CODE REVIEW

**Comment by idleberg** [comment]
First of all a big WOW! Thanks for these changes, I might need some time to go through these. I will come back to this later in the week.

**Comment by imbrish** [comment]
To make it a bit easier for you, I think looking through commits may not help, and it's a better idea to just look at the final version of the files (ie. please don't make me squash the commits 😅)

The basic flow is that:

- In Inno Setup we match only preprocessor, comments and section, anything else would be invalid.
- Individual sections are then matched separately, as they have different semantics (compare Setup, Code, Messages, Tasks).
- Then section content is matched either Directives, Parameters, Pascal etc, anything else is again invalid.
- Finally we match the value of a parameter/directive up until line end or a separator.
- What is a valid value depends on the section/keyword so again multiple contexts are defined for values.

Syntax is well commented, so anything else should be self explanatory.

**Comment by idleberg** [comment]
Don't worry, I will not ask you to squash these. I actually prefer it that way. Just hold on a bit longer, might not get to it before the weekend.

**Comment by imbrish** [comment]
Thanks for merging. Do you plan to release a new version to package control?

**Comment by idleberg** [comment]
I still plan to support Sublime Text 2 and TextMate, so I still need to merge those changes into the old syntax files

**Comment by idleberg** [comment]
@imbrish Are you interest in taking over the repository? I haven't used Sublime Text in a while, so it's not at the top of my list to maintain the package

**Comment by imbrish** [comment]
1. I guess it's the trailing commas. Not a valid json, but Sublime Text accepts these just fine, so I kept it like that. Maybe you want to configure the linter accordingly? But I could also remove these in a PR if you prefer :)
2. I could surely help to maintain this repo. I'm still on the Sublime boat, alas it's purely free time thing for me, so supporting ST2 and TextMate won't be on my priority list.

**Pull request merged**
