### PR TITLE
Linting and lint popup

### PR DESCRIPTION
**Pull request by Templar-von-Midgard**

### CODE REVIEW

**Comment by idleberg** [comment]
Thanks again, that's some amazing work! However, before committing further changes, please note I changed a couple of details in the meantime. I'm also wondering whether it's appropriate to change the scope of Inno Pascal to `source.pascal.inno`. What do you think?

**Comment by Templar-von-Midgard** [comment]
I absolutely agree with the renaming.
Also, take a look at my fork, I implemented a simple 'go to definition' and 'find all references' feature, and also refined the syntax highlighting.
I need to test and stabilize things a bit more, and also rebase, and then I will put up another PR.
Though this will only happen on monday or tuesday.

**Comment by idleberg** [comment]
Thanks, much appreciated

**Comment by idleberg** [comment]
Could you please explain what `sublime-innosetup.py` is supposed to do and how to use it?

**Pull request merged**
